### ISSUE TITLE
Grey bar [Windows 11 beta build 22621.1] [qBittorrent 4.4.3 x64, Qt 6]

### ISSUE THREAD

**Issue by KrazyLurt** [witalihirsch/qBitTorrent-Windows11-theme#1]
![bar-issue](https://user-images.githubusercontent.com/75538575/171919447-e46eab05-66d1-4123-871f-69848be69f88.png)

I've been using Mica For Everyone for quite a while, no real issues.
Theme looks really great overall, I hope this can be fixed.

[Windows 11 beta build 22621.1]
[qBittorrent 4.4.3 x64, Qt 6]

**Comment by KrazyLurt** [comment]
It's related to Qt 6 as qBittorrent Qt 5 works with the theme.

**Comment by witalihirsch** [comment]
> It's related to Qt 6 as qBittorrent Qt 5 works with the theme.

When qBitTorrent on Qt6 becomes more popular I'll change
